### PR TITLE
fix(convert): handle file names with multiple dots

### PR DESCRIPTION
**Pull request by luytena**
Ensure files with names containing dots in addition to the dot before the extension are handled correctly. The converted file name should correspond to the original file name replacing only the extension.

### CODE REVIEW

**Comment by luytena** [comment]
Due to issues with my current setup, I was unable to test the fix (besides through the test). @StephanH90 could you please take a moment to test the conversion to PDF for a file containing multiple dots?

**Review by StephanH90 — APPROVED** [review]
LGTM

**Comment by StephanH90** [comment]
I checked it out on my computer and the conversion works fine with the new testfile: `2023.test.test.docx-template.docx`

**Comment by luytena** [comment]
Awesome, thanks!

**Pull request merged**
